version: '3.8'

services:
  pubsub-emulator:
    build: .
    environment:
      - PUBSUB_PROJECT=test-project
      - PUBSUB_TOPIC=testnew,testold
      - PUBSUB_SUBSCRIPTION=subnew,subold
      - PUBSUB_PORT=8085