name: Publish Docker image

on:
  release:
    types: [published]

env:
  DOCKER_BUILD_CACHE_SCOPE: pubsub-emulator

jobs:
  verify-image:
    name: Verify Emulator Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - run: bash verify.bash

  publish_to_registry:
    needs: verify-image
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}    

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: | 
            dipjyotimetia/pubsub-emulator
            ghcr.io/${{ github.repository_owner }}/pubsub-emulator
          flavor: |
            latest=auto
          tags: |
              type=sha
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}  

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.ref_name }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }},ignore-error=true

      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

